spring.application.name=tic-tac-toe

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/tic_tac_toe_db

# Logging
spring.data.mongodb.auto-index-creation=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
server.port=${PORT:8080}
